// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl6y9Lz_Von0QsA9cHYYio-IFhGxgUuWc',
    appId: '1:853981284138:ios:257943f2186e9882ef4053',
    messagingSenderId: '853981284138',
    projectId: 'ayna-a6f60',
    storageBucket: 'ayna-a6f60.appspot.com',
    iosBundleId: 'com.example.ayna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfF5wKOvluSIm6gTwpyaa4UQeFaiOH3io',
    appId: '1:853981284138:web:54a6c985ba7486a8ef4053',
    messagingSenderId: '853981284138',
    projectId: 'ayna-a6f60',
    authDomain: 'ayna-a6f60.firebaseapp.com',
    storageBucket: 'ayna-a6f60.appspot.com',
    measurementId: 'G-6JH992PDKV',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfF5wKOvluSIm6gTwpyaa4UQeFaiOH3io',
    appId: '1:853981284138:web:54a6c985ba7486a8ef4053',
    messagingSenderId: '853981284138',
    projectId: 'ayna-a6f60',
    authDomain: 'ayna-a6f60.firebaseapp.com',
    storageBucket: 'ayna-a6f60.appspot.com',
    measurementId: 'G-6JH992PDKV',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl6y9Lz_Von0QsA9cHYYio-IFhGxgUuWc',
    appId: '1:853981284138:ios:257943f2186e9882ef4053',
    messagingSenderId: '853981284138',
    projectId: 'ayna-a6f60',
    storageBucket: 'ayna-a6f60.appspot.com',
    iosBundleId: 'com.example.ayna',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfsb_vfHPdeGFB4dqfjd27FO3GqdQ8pQ8',
    appId: '1:853981284138:android:99427ce2cddc90c4ef4053',
    messagingSenderId: '853981284138',
    projectId: 'ayna-a6f60',
    storageBucket: 'ayna-a6f60.appspot.com',
  );

}